### ISSUE TITLE
Unit strategy

### ISSUE THREAD

**Issue by jesper-friis** [EMMC-ASBL/oteapi-dlite#201]
Strategy for adding units.

A intended basic use should be to specify one or more unit ontologies, with EMMO being the default. However, adding a new unit to the ontologies is often time-consuming, so we also need a simple way to specify new units. That can be done with triples:

```yaml
- configurations:
    clear: True  # Whether to start with a blank unit registry
    prefixes:
      emmo: http://emmo.info/emmo#
      oteio: http://emmo.info/oteio#
      onto: http://example.com/onto#
    ontologies:  # Ontologies to load units from
      emmo: emmo-based
    triples:
      - [onto:DogYear, oteapi:hasUnitDef, "dog_year = 52 * day = DogYear"]
```
